// Property decision guidance, not claims about neighborhood-specific defects.
export const LOCAL_INSPECTION_CONTENT: Record<string, { title: string; intro: string; preparation: string }> = {
  'avon-in': { title: 'Make the inspection part of your property decision.', intro: 'For an Avon purchase or sale, a sewer scope adds evidence about the accessible line to the other information you are reviewing. Share the inspection deadline and any earlier report so we can agree on the question the visit needs to answer.', preparation: 'Ask the seller or occupant where the cleanout is and who can provide entry. If access is uncertain, tell us before booking; alternate access and its price need agreement.' },
  'brownsburg-in': { title: 'Understand a blockage that keeps returning.', intro: 'When a Brownsburg sewer has been cleared but the same symptoms return, the useful question is what can actually be observed. Tell PSI which fixtures are affected, when the last clearing occurred and whether any footage exists.', preparation: 'The report separates visible buildup or defects from possible explanations. If standing water or a blockage stops the camera, we identify the accessible section and discuss the remaining question.' },
  'carmel-in': { title: 'Match the inspection to the property you manage.', intro: 'A Carmel owner or manager may need one line checked or a record of several accessible laterals. Identify the buildings and access points first so each recording can be connected to the line it documents.', preparation: 'Coordinate occupant access and operating restrictions before the visit. For repeat condition checks, discuss which sections need comparable records and how the agreed scope may change between visits.' },
  'fishers-in': { title: 'Keep your recording useful after closing.', intro: 'A Fishers homebuyer can use a sewer inspection to understand the visible condition at the time of the visit. Keep the video and written findings alongside the property documents so an observation can be reviewed later.', preparation: 'Share transaction timing and known sewer access. A clear accessible section is useful evidence, but it does not establish the condition of an unseen section or guarantee future performance.' },
  'franklin-in': { title: 'Check what the proposed repair is based on.', intro: 'Before deciding about a sewer repair at a Franklin property, gather the existing recording, written findings and proposed scope. PSI can help distinguish a visible condition from a suspected cause and explain what another inspection would add.', preparation: 'Use the free video review when you already have usable footage, or ask about an on-site scope when information is missing. Reviewing evidence does not commit you to an IDC service.' },
  'geist-indianapolis-in': { title: 'Confirm the address and the line to be inspected.', intro: 'For a property in the Geist area, provide the full street address and municipality so we can confirm availability. Tell us whether the concern is the sanitary sewer, an accessible drain or a suitable pump system; these may require different access and equipment.', preparation: 'If locating is part of the request, agree on the desired surface marks or route sketch. Signal and access limits apply, and any depth reading is an estimate rather than a surveyed measurement.' },
  'greenfield-in': { title: 'Start with the symptoms, then check the evidence.', intro: 'A Greenfield homeowner does not need to diagnose the sewer before contacting PSI. Describe which fixtures are affected, how often the problem occurs and whether anything recently changed. That history helps us set a useful inspection scope.', preparation: 'Keep previous cleaning or inspection records handy. We document observed conditions separately from possible causes and explain any further investigation before you decide about it.' },
  'greenwood-in': { title: 'Know which line the report describes.', intro: 'For a Greenwood investment or rental property, identify the unit, shared areas and known access points. Where more than one line needs attention, the scope should make clear which lines are included and how they will be identified in the findings.', preparation: 'Arrange entry with the occupant and share available plans as background information. A plan does not prove the actual route; a trace or camera view has its own access and visibility limits.' },
  'indianapolis-in': { title: 'An inspection shaped around your Indianapolis address.', intro: 'The right starting point depends on the property and the question, whether you are buying a home, reviewing an existing sewer report or investigating recurring backups. Give us the address and concern so we can confirm access, scope and availability.', preparation: 'Tell us if entry must be coordinated with a tenant, agent or manager. PSI records what is accessible and explains the limitations; any cleaning, alternate access or additional lines are discussed separately.' },
  'noblesville-in': { title: 'Separate the observation from the next-step recommendation.', intro: 'When reviewing a sewer concern in Noblesville, the recording should help explain the finding. Ask what is visible, what remains uncertain and why an option is being proposed. PSI keeps these distinctions clear in the inspection discussion.', preparation: 'An existing report may be enough to support a quote. Share its job reference first; new footage may be appropriate if conditions changed or the earlier recording leaves a relevant section unseen.' },
  'plainfield-in': { title: 'Plan access before the inspection day.', intro: 'For a Plainfield inspection, knowing where the cleanout is can make the scope and price easier to confirm. If you cannot find it, say so; PSI can discuss the available access and whether a non-excavating locate is feasible.', preparation: 'Do not assume roof, toilet or crawl-space access is suitable at every property. We confirm the method and any listed additional charge before that work is approved.' },
  'westfield-in': { title: 'Document a useful starting condition.', intro: 'A Westfield property owner may want a sewer condition record before a purchase, at a change of tenancy or to compare with a later concern. Explain the purpose so the recording and line identification are useful for that decision.', preparation: 'For scheduled repeat checks, agree on the scope and timing individually. A condition inspection records accessible conditions during that visit; it cannot promise that a line will remain clear.' },
  'zionsville-in': { title: 'Put the video and the explanation together.', intro: 'If a Zionsville sewer inspection leaves you with questions, ask to review the recording alongside the written findings. Footage references can help identify what the inspector observed, while the explanation should state what could not be confirmed.', preparation: 'Keep the recording when considering options from IDC or another provider. If the accessible findings support no additional work, we say so; unresolved sections are still identified as limitations.' },
}
